export const categories = [
  {
    title: 'New',
    slug: 'recent',
    filter: '',
    sort: 'newest',
    range: 90,
  },
  {
    title: 'Trending',
    slug: 'trending',
    filter: '',
    sort: 'mostpopular',
    range: 60,
  },
  {
    title: 'For You',
    slug: 'foryou',
    filter: 'foryou',
    sort: 'newest',
    range: 30,
  },
  {
    title: 'Following',
    slug: 'following',
    filter: 'following',
    sort: 'newest',
    range: 900,
  },
  {
    title: 'Popular',
    slug: 'popular',
    filter: '',
    sort: 'mostpopular',
    range: 900,
  },
  {
    title: 'Open to Collaboration',
    slug: 'opentocollab',
    filter: 'opentocollab',
    sort: 'newest',
    range: 900,
  },
  {
    title: 'Apps',
    slug: 'apps',
    filter: 'apps',
    sort: 'newest',
    range: 900,
  },
  {
    title: 'Games',
    slug: 'games',
    filter: 'games',
    sort: 'newest',
    range: 900,
  },
  {
    title: 'Open Source',
    slug: 'opensource',
    filter: 'opensource',
    sort: 'newest',
    range: 900,
  },
  {
    title: 'Tools',
    slug: 'tools',
    filter: 'tools',
    sort: 'newest',
    range: 900,
  },
  {
    title: 'Frontend',
    slug: 'frontend',
    filter: 'frontend',
    sort: 'newest',
    range: 900,
  },
  {
    title: 'Backend',
    slug: 'backend',
    filter: 'backend',
    sort: 'newest',
    range: 900,
  },
  {
    title: 'Full Stack',
    slug: 'fullstack',
    filter: 'fullstack',
    sort: 'newest',
    range: 900,
  },
  {
    title: 'Cloud',
    slug: 'cloud',
    filter: 'cloud',
    sort: 'newest',
    range: 900,
  },
  {
    title: 'AI',
    slug: 'ai',
    filter: 'AI',
    sort: 'newest',
    range: 900,
  },
  {
    title: 'Machine Learning',
    slug: 'machinelearning',
    filter: 'machine learning',
    sort: 'newest',
    range: 900,
  },
  {
    title: 'Components',
    slug: 'components',
    filter: 'components',
    sort: 'newest',
    range: 900,
  },
  {
    title: 'Libraries',
    slug: 'libraries',
    filter: 'libraries',
    sort: 'newest',
    range: 900,
  },
  {
    title: 'Infrastructure',
    slug: 'infrastructure',
    filter: 'infrastructure',
    sort: 'newest',
    range: 900,
  },
  {
    title: 'Automation',
    slug: 'automation',
    filter: 'automation',
    sort: 'newest',
    range: 900,
  },
  {
    title: 'DevOps',
    slug: 'devops',
    filter: 'devops',
    sort: 'newest',
    range: 900,
  },
  {
    title: 'Security',
    slug: 'security',
    filter: 'security',
    sort: 'newest',
    range: 900,
  },
  {
    title: 'Databases',
    slug: 'databases',
    filter: 'databases',
    sort: 'newest',
    range: 900,
  },
  {
    title: 'Data Science',
    slug: 'datascience',
    filter: 'data science',
    sort: 'newest',
    range: 900,
  },
];

export const techFilter = [
  'react',
  'java',
  'JavaScript',
  'typescript',
  'node',
  'PHP',
  'python',
  'c#',
  'ruby',
  'go',
];

export const categoriesFilter = [
  'apps',
  'games',
  'opensource',
  'tools',
  'infrastructure',
  'databases',
  'data science',
  'frontend',
  'backend',
  'fullstack',
  'cloud',
  'AI',
  'machine learning',
  'components',
  'libraries',
  'automation',
  'devops',
  'security',
];

export const rangeFilter = [
  { value: 7, label: 'Posted this week' },
  { value: 30, label: 'Posted this month' },
  { value: 365, label: 'Posted this year' },
  { value: 900, label: 'All time' },
];

export const sortFilter = [
  { value: 'mostpopular', label: 'Popular' },
  { value: 'newest', label: 'Newest' },
  { value: 'oldest', label: 'Oldest' },
];
