export const CategoriesFilter = [
  // {
  //   label: 'All',
  //   slug: '',
  //   term: '',
  // },
  {
    label: 'Open to Collaboration',
    slug: 'opentocollab',
    term: 'opentocollab',
    title: 'Projects open to collaboration',
    desc: 'Find projects and connect to developers looking for collaborators',
  },
  {
    label: 'Apps',
    slug: 'apps',
    term: 'apps',
    title: 'Full stack apps projects',
    desc: 'Cool apps built by the community',
  },
  {
    label: 'Games',
    slug: 'games',
    term: 'games',
    title: 'Games',
    desc: 'Explore cool games projects showcased',
  },
  {
    label: 'Open Source',
    slug: 'opensource',
    term: 'opensource',
    title: '',
    desc: 'Developer projects that are open source',
  },
  {
    label: 'Tools',
    slug: 'tools',
    term: 'tools',
    title: 'Tools built by devs',
    desc: 'Useful tools built by developers',
  },
  {
    label: 'Frontend',
    slug: 'frontend',
    term: 'frontend',
    title: 'Awesome frontend projects',
    desc: 'Browse projects that are all things frontend',
  },
  {
    label: 'Backend',
    slug: 'backend',
    term: 'backend',
    title: 'Solid, scalable backend projects',
    desc: 'Browse projects that are all things backend',
  },
  {
    label: 'Full Stack',
    slug: 'fullstack',
    term: 'fullstack',
    title: 'Frontend vs backend',
    desc: 'Browse these awesome full stack developer projects',
  },
  {
    label: 'Cloud',
    slug: 'cloud',
    term: 'cloud',
    title: '',
    desc: 'Projects utilizing the power of the cloud',
  },
  {
    label: 'AI',
    slug: 'ai',
    term: 'ai',
    title: 'All things AI',
    desc: 'The world as become obsessed with AI, check out these projects',
  },
  {
    label: 'Machine Learning',
    slug: 'machinelearning',
    term: 'machine learning',
    title: '',
    desc: 'Projects that utilize the power of machine learning',
  },
  {
    label: 'Components',
    slug: 'components',
    term: 'components',
    title: 'We love components',
    desc: 'Useful components showcased by developers',
  },
  {
    label: 'Libraries',
    slug: 'libraries',
    term: 'libraries',
    title: 'Useful library projects',
    desc: 'Check out these libraries showcased',
  },
  {
    label: 'Infrastructure',
    slug: 'infrastructure',
    term: 'infrastructure',
    title: '',
    desc: 'Projects that utilize and optimise our infrastructure',
  },
  {
    label: 'Automation',
    slug: 'automation',
    term: 'automation',
    title: '',
    desc: 'Anything that can be repeated, automate it',
  },
  {
    label: 'DevOps',
    slug: 'devops',
    term: 'devops',
    title: '',
    desc: 'Developer utilities for the DevOps person in you',
  },
  {
    label: 'Security',
    slug: 'security',
    term: 'security',
    title: '',
    desc: 'Everything we build needs to be secure, check these projects out',
  },
  {
    label: 'Databases',
    slug: 'databases',
    term: 'databases',
    title: '',
    desc: 'Think you know all about data storage? Think again',
  },
  {
    label: 'Data Science',
    slug: 'datascience',
    term: 'data science',
    title: 'Data is power',
    desc: 'Awesome projects utilizing the power of Data',
  },
];

export const RangeFilter = [
  { type: 'range', days: 7, label: 'Posted this week' },
  { type: 'range', days: 30, label: 'Posted this month' },
  { type: 'range', days: 365, label: 'Posted this year' },
  { type: 'range', days: 900, label: 'All time' },
];

export const SortFilter = [
  { type: 'sort', orderBy: 'newest', label: 'Sort by latest' },
  { type: 'sort', orderBy: 'mostpopular', label: 'Sort by popular' },
  { type: 'sort', orderBy: 'oldest', label: 'Sort by oldest' },
];

export const StackFilter = {
  label: 'Stack',
  icon: 'FiCode',
  stacks: [
    {
      slug: 'javascript',
      label: 'JavaScript',
      icon: 'SiJavascript',
      terms: 'javascript',
    },
    {
      slug: 'react',
      label: 'React',
      icon: 'SiReact',
      terms: 'react,reactjs',
    },
    {
      slug: 'vue',
      label: 'Vue',
      icon: 'SiVuedotjs',
      terms: 'vue,vuejs',
    },
    {
      slug: 'nextjs',
      label: 'NextJS',
      icon: 'SiNextdotjs',
      terms: 'nextjs',
    },
    {
      slug: 'nuxtjs',
      label: 'NuxtJS',
      icon: 'SiNuxtdotjs',
      terms: 'nuxt,nuxtjs',
    },
    {
      slug: 'gatsby',
      label: 'Gatsby',
      icon: 'SiGatsby',
      terms: 'gatsby',
    },
    {
      slug: 'angular',
      label: 'Angular',
      icon: 'SiAngular',
      terms: 'angular',
    },
    {
      slug: 'tailwindcss',
      label: 'Tailwind',
      icon: 'SiTailwindcss',
      terms: 'tailwind,tailwindcss',
    },
    {
      slug: 'chakra',
      label: 'ChakraUI',
      icon: 'SiChakraui',
      terms: 'chakra,chakraui',
    },
    {
      slug: 'bootstrap',
      label: 'Bootstrap',
      icon: 'SiBootstrap',
      terms: 'bootstrap',
    },
    {
      slug: 'redux',
      label: 'Redux',
      icon: 'SiRedux',
      terms: 'redux',
    },
    {
      slug: 'svelte',
      label: 'Svelte',
      icon: 'SiSvelte',
      terms: 'svelte',
    },
  ],
};
